[package]
name = "badlogvis"
version = "0.1.0"
authors = ["Dominik Winecki <dominikwinecki@gmail.com>"]

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"
serde = "*"
serde_json = "*"
serde_derive = "*"
